import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

import "../globals.css";
import "../../../public/assets/css/bootstrap.min.css";
import "../../../public/assets/css/plugins.css";
import "../../../public/assets/css/style.css";

import { CartProvider } from "../../components/header/CartContext";
import { WishlistProvider } from "../../components/header/WishlistContext";
import { CompareProvider } from "../../components/header/CompareContext";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const locales = ["en", "ar"];

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Busket E-Commerce",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/images/fav.ico",
        type: "image/x-icon",
      },
    ],
  },
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  const resolvedParams = await params;
  const locale = resolvedParams?.locale;
  const activeLocale = locale || "ar";

  // Validate that the locale is supported
  if (!locales.includes(activeLocale)) {
    notFound();
  }

  // Obtain translation messages
  const messages = await getMessages();

  return (
    <html lang={activeLocale} dir={activeLocale === "ar" ? "rtl" : "ltr"}>
      <body className={notoSans.className}>
        <NextIntlClientProvider locale={activeLocale} messages={messages}>
          <CompareProvider>
            <WishlistProvider>
              <CartProvider>
                {children}
                <ToastContainer position="top-right" autoClose={3000} />
              </CartProvider>
            </WishlistProvider>
          </CompareProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}